- hosts: frontends
  gather_facts: false
  tasks:
  - name: Check webserver for correct response
    uri:
      url: "http://localhost/ping"
      return_content: yes
    register: result
    until: '"alive" in result.content'
    retries: 10
    delay: 1
