- name: Gathering information about OSP QA env
  hosts: workstation
  gather_facts: false
  roles:
  - osp-facts

- name: Smoke test
  hosts: workstation
  gather_facts: false
  tasks:
  - name: Check webserver for correct response
    uri:
      url: "http://{{ hostvars[item]['inventory_hostname'] }}/ping"
      return_content: yes
    until: '"alive" in result.content'
    retries: 10
    delay: 1
    register: result
    loop: "{{ groups['frontends'] }}"

